M48
; DRILL file {KiCad (6.0.10)} date Sun Mar 26 17:01:15 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-26T17:01:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X90.8Y-110.0
X90.8Y-110.0
X93.091Y-54.864
X162.8Y-53.8
X163.2Y-111.8
T0
M30
