M48
; DRILL file {KiCad (6.0.10)} date Wed Apr  5 19:00:52 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-05T19:00:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.6417Y-4.3504
X3.6417Y-4.3504
X3.665Y-2.16
X5.83Y-2.165
X5.8465Y-4.3504
T0
M30
